<!DOCTYPE html>

<html lang="en">
<!-- Place this folder inside the htdocs folder (generated by XAMPP), or at least outside the root folder, for security! -->
<!-- If you wish to place it elsewhere, you must code its location into the necessary php files to ensure a successful connection to the database! -->
  <?php
	$serverName = "___"; // Replace underscore with your server name
	$uid = "___";   // Replace underscore with your user ID
	$pwd = "___";  // Replace underscore with your password  
	$databaseName = "dbHistoricalSite";
   ?>
</html>