<!DOCTYPE html>

<html lang="en">
<!-- Place this folder inside the htdocs folder (generated by XAMPP) for security! -->
<!-- If you wish to place it elsewhere, you must code its location into the necessary php files to ensure a successful connection to the database! -->
  <?php
	$serverName = "DESKTOP-EB14AA8"; //tcp:myserver.database.windows.net,1433
	$uid = "adminWebsite";   
	$pwd = "popred1297djnfjds98u4jks[appl09ddf";  
	$databaseName = "dbHistoricalSite";
   ?>
</html>